apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      labels:
        app: myapp
      name: myapp-pod
    spec:
      containers:
        - image: nginx:1.12
          name: nginx-container
  replicas: 3
  selector:
    matchLabels:
      app: myapp